// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storage

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Post struct {
	ID          uuid.UUID
	Title       string
	Description string
	Content     string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	PublishedAt sql.NullTime
	IsDraft     bool
}
