// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package storage

import (
	"context"

	"github.com/google/uuid"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (id, title, description, content, is_draft)
VALUES (?, ?, ?, ?, ?)
RETURNING id, title, description, content, created_at, updated_at, published_at, is_draft
`

type CreatePostParams struct {
	ID          uuid.UUID
	Title       string
	Description string
	Content     string
	IsDraft     bool
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Content,
		arg.IsDraft,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.IsDraft,
	)
	return i, err
}

const getPostByID = `-- name: GetPostByID :one
SELECT id, title, description, content, created_at, updated_at, published_at, is_draft FROM posts
WHERE id = ?
`

func (q *Queries) GetPostByID(ctx context.Context, id uuid.UUID) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPostByID, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.IsDraft,
	)
	return i, err
}

const getPostByTitle = `-- name: GetPostByTitle :one
SELECT id, title, description, content, created_at, updated_at, published_at, is_draft FROM posts
WHERE title = ?
`

func (q *Queries) GetPostByTitle(ctx context.Context, title string) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPostByTitle, title)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.IsDraft,
	)
	return i, err
}

const listPosts = `-- name: ListPosts :many
SELECT id, title, description, content, created_at, updated_at, published_at, is_draft FROM posts
ORDER BY created_at
`

func (q *Queries) ListPosts(ctx context.Context) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, listPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublishedAt,
			&i.IsDraft,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removePost = `-- name: RemovePost :exec
DELETE FROM posts
WHERE id = ?
`

func (q *Queries) RemovePost(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, removePost, id)
	return err
}

const updatePostContent = `-- name: UpdatePostContent :exec
UPDATE posts
SET content = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdatePostContentParams struct {
	Content string
	ID      uuid.UUID
}

func (q *Queries) UpdatePostContent(ctx context.Context, arg UpdatePostContentParams) error {
	_, err := q.db.ExecContext(ctx, updatePostContent, arg.Content, arg.ID)
	return err
}
